/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.', className: 'cat' }],
  tutorialSidebar: [
    'introduction',
    {
      type: 'category',
      label: 'React Starter',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Getting started',
          collapsed: false,
          items: [
            {
              type: 'autogenerated',
              dirName: 'react-starter/getting-started',
            },
          ],
        },
        {
          type: 'category',
          label: 'Basics',
          collapsed: false,
          items: [
            {
              type: 'autogenerated',
              dirName: 'react-starter/basics',
            },
          ],
        },
        {
          type: 'category',
          label: 'Routing',
          collapsed: false,
          items: [
            {
              type: 'autogenerated',
              dirName: 'react-starter/routing',
            },
          ],
        },
        {
          type: 'category',
          label: 'Search',
          collapsed: false,
          items: [
            {
              type: 'doc',
              label: 'Overview',
              id: 'react-starter/search/search'
            },
            {
              type: 'category',
              label: 'Hooks',
              collapsed: false,
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'react-starter/search/hooks',
                },
              ],
            }

          ]
        },
        {
          type: 'category',
          label: 'Advanced',
          collapsed: false,
          items: [
            {
              type: 'category',
              label: 'Redux',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'react-starter/advanced/redux',
                }
              ]
            },
            {
              type: 'doc',
              label: 'Composer',
              id: 'react-starter/advanced/composer',
            },
            {
              type: 'doc',
              label: 'Canvas',
              id: 'react-starter/advanced/canvas',
            },
            {
              type: 'category',
              label: 'Deployment',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'react-starter/advanced/deployment',
                }
              ]
            },
            {
              type: 'autogenerated',
              dirName: 'react-starter/advanced/tips',
            },
          ],
        },
      ]
    },
    {
      type: 'category',
      label: 'Node Starter',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'node-starter',
        },
      ],
    }
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
