/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.', className: 'cat' }],
  tutorialSidebar: [
    'introduction',
    {
      type: 'category',
      label: 'React Starter',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Getting started',
          collapsed: false,
          items: [
            {
              type: 'autogenerated',
              dirName: 'react-starter/getting-started',
            },
          ],
        },
        {
          type: 'category',
          label: 'Basics',
          collapsed: false,
          items: [
            {
              type: 'autogenerated',
              dirName: 'react-starter/basics',
            },
          ],
        },
        {
          type: 'category',
          label: 'Routing',
          collapsed: false,
          items: [
            {
              type: 'autogenerated',
              dirName: 'react-starter/routing',
            },
          ],
        },
        {
          type: 'category',
          label: 'Search',
          collapsed: false,
          items: [
            {
              type: 'autogenerated',
              dirName: 'react-starter/search',
            },
          ],
        },
        {
          type: 'category',
          label: 'Advanced',
          collapsed: false,
          items: [
            {
              type: 'category',
              label: 'Redux',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'react-starter/advanced/redux',
                }
              ]
            },
            {
              type: 'autogenerated',
              dirName: 'react-starter/advanced/tips',
            },
          ],
        },
      
      ]
    }
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
